spring.application.name=backendstreaming



# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=steepbs
spring.datasource.password=angela
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Ruta donde se guardan los archivos de audio
app.audio.path=/home/steepdev/Music/

# Tamaño máximo de archivo
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB